prowjob_namespace: "default"

in_repo_config:
  enabled:
    "*": true

tide:
  target_url: http://<domain>/tide # update this domain
  queries:
    - repos:
        - Lonor/kubernetes-springboot-demo
      labels:
        - lgtm
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
    orgs:
      org:
        required-contexts:
          - "check-required-for-all-repos"
        repos:
          repo:
            required-contexts:
              - "check-required-for-all-branches"
            branches:
              branch:
                from-branch-protection: false
                required-contexts:
                  - "required_test"
                optional-contexts:
                  - "optional_test"
#             args: [ "-c", "mkdir -p /${REPO_NAME}; cd /${REPO_NAME}; git init; git remote add origin https://github.com/${REPO_OWNER}/${REPO_NAME}.git; git fetch origin pull/${PULL_NUMBER}/head:pr-${PULL_NUMBER}; git checkout pr-${PULL_NUMBER}; pwd; mvn test " ]
presubmits:
  Lonor/kubernetes-springboot-demo:
    - name: spring
      decorate: false
      always_run: false
      spec:
        containers:
          - image: maven:3.6-jdk-8
            command: [ "/bin/sh", "-c" ]
            args:
              - |
                mkdir -p /root/.m2
                curl -L https://gitee.com/lawrence2019/codes/rh8wo4g217au36lzyx0km20/raw\?blob_name\=settings.xml -o /root/.m2/settings.xml
                mkdir -p /${REPO_NAME}
                cd /${REPO_NAME}
                git init
                git remote add origin https://github.com/${REPO_OWNER}/${REPO_NAME}.git
                git fetch origin pull/${PULL_NUMBER}/head:pr-${PULL_NUMBER}
                git checkout pr-${PULL_NUMBER}
                mvn test
            resources:
              requests:
                cpu: "2000m"
                memory: "1536Mi"