apiVersion: apps/v1 # 1.19
kind: Deployment
metadata:
  name: spring-boot
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: registry.cn-shanghai.aliyuncs.com/dockerhub2019/spring-ingress:0.0.2
          ports:
            - containerPort: 8080
              name: spring-rest
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: redis-svc.default.svc.cluster.local
            - name: REDIS_PORT
              value: '6379'
            - name: JAVA_OPTS
              value: '-XX:+UseG1GC'
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              memory: 512Mi
              cpu: 50m
          lifecycle:
            preStop: # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#cloud-deployment-kubernetes
              exec:
                command: [ "sh", "-c", "sleep 15" ]